name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: cd GoodLinkOrBadLink && dotnet restore
    - name: Build
      run: cd GoodLinkOrBadLink && dotnet run
    - name: Test
      run: cd GoodLinkOrBadLink.Test && dotnet test
